ComputerRankExam/Controllers/LoginController.cs
using System;
using System.Web;
using System.Web.Mvc;
using Sower.CommFunction;
using ComputerRankExam.Models;
using Sower.Business;
using ComputerRankExam.App_Start;

namespace ComputerRankExam.Controllers
{
    public class LoginController : Controller
    {
        AverageUserService userService = new AverageUserService();
        LearnCardService cardService = new LearnCardService();

        /// <summary>
        /// 获取用户名
        /// </summary>
        public string UserName
        {
            get
            {
                HttpCookie _cookie = Request.Cookies["AverageUser"];
                if (_cookie == null) return "";
                else return _cookie["UserName"];
            }
        }
        [ChildActionOnly]
        public ActionResult LoginTop()
        {
            if (UserName != "")
            {
                if (CommonUnits.CheckNumber(UserName))
                {
                    var _card = cardService.Find(UserName);
                    return PartialView("~/Views/Login/LoginTopCardPass.cshtml", _card);
                }
                else
                {
                    var _user = userService.Find(UserName);
                    return PartialView("~/Views/Login/LoginTopUserPass.cshtml", _user);
                }
            }
            else
            {
                return PartialView();
            }
        }

        /// <summary>
        /// 退出登录
        /// </summary>
        /// <returns></returns>
        [HttpGet]
        public ActionResult LoginExit()
        {
            HttpCookie cookie = Request.Cookies["AverageUser"];
            if (cookie != null)
            {
                cookie.Expires = DateTime.Now.AddDays(-2);
                Response.Cookies.Set(cookie);

            }
            Notice _n = new Notice
            {
                Title = "成功退出",
                Details = "您已经成功退出！",
                DwellTime = 5,
                NavigationName = "网站首页",
                NavigationUrl = Url.Action("Index", "Home")
            };
            return RedirectToAction("Notice", "Prompt", _n);
        }
    }
}

ComputerRankExam/Controllers/menuController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ComputerRankExam.Models;
using Sower.Business;
using Sower.Model;

namespace ComputerRankExam.Controllers
{
    public class MenuController : Controller
    {
        //
        // GET: /menu/
        [ChildActionOnly]
        public ActionResult IndexNav(string id)
        {
            NavigateViewModel viewModel = new NavigateViewModel();
            if (id == "0")
            {
                viewModel.css_index = "active";
            }
            else
            {
                viewModel.css_index = "";
            }

            if (id == "1")
            {
                viewModel.css_1 = "active";
            }
            else
            {
                viewModel.css_1 = "";
            }

            if (id == "2")
            {
                viewModel.css_2 = "active";
            }
            else
            {
                viewModel.css_2 = "";
            }

            if (id == "3")
            {
                viewModel.css_3 = "active";
            }
            else
            {
                viewModel.css_3 = "";
            }

            if (id == "4")
            {
                viewModel.css_4 = "active";
            }
            else
            {
                viewModel.css_4 = "";
            }

            if (id == "5")
            {
                viewModel.css_5 = "active";
            }
            else
            {
                viewModel.css_5 = "";
            }

            if (id == "6")
            {
                viewModel.css_6 = "active";
            }
            else
            {
                viewModel.css_6 = "";
            }

            BLL_ExamType bll = new BLL_ExamType();
            T_ExamType model = bll.GetExamType("1");
            viewModel.ExamDomain = model.ExamDomain;
            return View(viewModel);
        }
    }
}

ComputerRankExam/Views/Shared/_Column.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <meta name="keywords" content="" />
    <meta name="description" content="" />

    <title>@ViewBag.Title-计算机等级考试</title>

    @Styles.Render("~/Css/column")
    <!--[if lt IE 8]>@Styles.Render("~/Css/column_ie6")<![endif]-->

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/online")
    @RenderSection("scripts", required: false)
</head>
<body>
    <!---start-header---->
    <div class="header">
        <div class="top-header">
            <div class="wrap">
                <div class="top-header-left">
                    0371-63461180
                </div>
                <div class="right-left" id="ajaxlogin" style="padding-top:6px;">
                    @{Html.RenderAction("LoginTop", "Login");}
                </div>
                <div class="clear"> </div>
            </div>
        </div>
        <div class="main-header">
            <div class="wrap" style="width:90%;">
                <div class="logo">
                    <a href="@Url.Action("Index", "Home", routeValues: new { Area = "" })">
                        <img src="@Url.Content("~/content/images/common/logo.png")" title="logo" />
                    </a>
                </div>
                <div style="float:left;">
                    <img src="@Url.Content("~/content/images/common/test_center.png")" />
                </div>
                @*<div class="social-links">
                        <ul>
                            <li><a href="#"><img src="@Url.Content("~/content/images/facebook.png")" title="facebook" /></a></li>
                            <li><a href="#"><img src="@Url.Content("~/content/images/twitter.png")" title="twitter" /></a></li>
                            <li><a href="#"><img src="@Url.Content("~/content/images/feed.png")" title="Rss" /></a></li>
                            <div class="clear"> </div>
                        </ul>
                    </div>*@
                <div class="clear"> </div>
            </div>
        </div>
        <div class="clear"> </div>
        <div class="menu">
            @{Html.RenderAction("Navigate", "Menu", new { id = @ViewBag.currentID });}
            <div class="clear"> </div>
        </div>
        <!---End-header---->
    </div>
    <!---End-header---->
    <!---start-content---->
    <div class="content">
        @RenderBody()
    </div>
    <!---end-content---->
    <!---start-footer---->
    <div class="footer">
        <div class="wrap">
            <div class="footer-grids">
                <div class="footer-grid" style="border:none">
                    <h3>新手指南</h3>
                    <ul>
                        <li><a href="#">如何在线做题</a></li>
                        <li><a href="#">如何组卷练习</a></li>
                        <li><a href="#">查看成绩和解析</a></li>
                        <li><a href="#">如何上传一份试卷</a></li>
                    </ul>
                </div>
                <div class="footer-grid">
                    <h3>会员服务</h3>
                    <ul>
                        <li><a href="#">免费注册</a></li>
                        <li><a href="#">充值</a></li>
                        <li><a href="#">成为VIP</a></li>
                        <li><a href="#">个人中心</a></li>
                    </ul>
                </div>
                <div class="footer-grid">
                    <h3>服务支持</h3>
                    <ul>
                        <li><a href="#">常见问题</a></li>
                        <li><a href="#">咨询客服</a></li>
                        <li><a href="#">高价收购试卷</a></li>
                        <li>&nbsp;</li>
                    </ul>
                </div>
                <div class="footer-grid">
                    <h3>联系方式</h3>
                    <ul>
                        <li><a href="#">周一至周五8:30-18:00</a></li>
                        <li><a href="#">0371-63461180</a></li>
                        <li>&nbsp;</li>
                        <li>&nbsp;</li>
                    </ul>
                </div>
                <div class="clear"> </div>
            </div>
            <div class="clear"> </div>
            <!---start-copy-right----->
            <div class="copy-tight">
                <p>
                    <a href="#">关于我们</a>&nbsp;|
                    <a href="#">网站导航</a>&nbsp;|
                    <a href="#">常见问题&帮助</a>&nbsp;|
                    <a href="#">免责声明</a>&nbsp;|
                    <a href="#">投诉&建议</a><br />
                    CopyRight 2009-2015 朔日测评 | 豫ICP备10203241号
                </p>
            </div>
            <!---End-copy-right----->
        </div>
    </div>
    <!---End-footer---->
</body>
</html>

ComputerRankExam/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <meta name="keywords" content="" />
    <meta name="description" content="" />

    <title>@ViewBag.Title-朔日测评-在线练习中心</title>

    @Styles.Render("~/Content/Css/style.css")
    @Styles.Render("~/Content/Css/lrtk.css")
    @Styles.Render("~/Content/Css/responsiveslides.css")
    <!--[if lt IE 8]>
    @Styles.Render("~/Content/Css/style_ie6.css");
    @Styles.Render("~/Content/Css/lrtk_ie6.css");
    @Styles.Render("~/Content/Css/responsiveslides_ie6.css");
    <![endif]-->
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/online")
    @RenderSection("scripts", required: false)
</head>
<body>
    <!---start-header---->
    <div class="header">
        <div class="top-header">
            <div class="wrap">
                <div class="top-header-left">
                    @*<p>&nbsp;0371-63461180 </p>*@
                    0371-63461180
                </div>
                <div class="right-left" id="ajaxlogin">
                    @{Html.RenderAction("LoginTop", "Login");}
                </div>
                <div class="clear"> </div>
            </div>
        </div>
        <div class="main-header">
            <div class="wrap">
                <div class="logo">
                    <a href="@Url.Action("Index", "Home", routeValues: new { Area = "" })">
                        <img src="@Url.Content("~/content/images/common/logo.png")" title="logo" />
                    </a>
                </div>
                <div style="float:left;">
                    <img src="@Url.Content("~/content/images/common/test_center.png")" />
                </div>
                @*<div class="social-links">
                        <ul>
                            <li><a href="#"><img src="@Url.Content("~/content/images/feed.png")" title="Rss" /></a></li>
                            <li><a href="#"><img src="@Url.Content("~/content/images/feed.png")" title="Rss" /></a></li>
                            <li><a href="#"><img src="@Url.Content("~/content/images/feed.png")" title="Rss" /></a></li>
                            <li><a href="#"><img src="@Url.Content("~/content/images/feed.png")" title="Rss" /></a></li>
                            <li><a href="#"><img src="@Url.Content("~/content/images/feed.png")" title="Rss" /></a></li>
                            <li><a href="#"><img src="@Url.Content("~/content/images/feed.png")" title="Rss" /></a></li>
                            <div class="clear"> </div>
                        </ul>
                    </div>*@
                <div class="clear"> </div>
            </div>
        </div>
        <div class="clear"> </div>
        <div class="menu">
            @{Html.RenderAction("IndexNav", "Menu", new { id = @ViewBag.currentID });}
            <!-- clear the floats if required -->
            <div class="clear"> </div>
            <!---End-header---->
        </div>
    </div>
    <!---end-header---->
    <div class="content">
        @RenderBody()
    </div>
    <!---start-footer---->
    <div class="footer">
        <div class="wrap">
            <div class="footer-grids">
                <div class="footer-grid">
                    <h3>新手指南</h3>
                    <ul>
                        <li><a href="#">如何在线做题</a></li>
                        <li><a href="#">如何组卷练习</a></li>
                        <li><a href="#">查看成绩和解析</a></li>
                        <li><a href="#">如何上传一份试卷</a></li>
                    </ul>
                </div>
                <div class="footer-grid">
                    <h3>会员服务</h3>
                    <ul>
                        <li><a href="#">免费注册</a></li>
                        <li><a href="#">充值</a></li>
                        <li><a href="#">成为VIP</a></li>
                        <li><a href="#">个人中心</a></li>
                    </ul>
                </div>
                <div class="footer-grid">
                    <h3>服务支持</h3>
                    <ul>
                        <li><a href="#">常见问题</a></li>
                        <li><a href="#">咨询客服</a></li>
                        <li><a href="#">高价收购试卷</a></li>
                        <li>&nbsp;</li>
                    </ul>
                </div>
                <div class="footer-grid">
                    <h3>联系方式</h3>
                    <ul>
                        <li><a href="#">周一至周五8:30-18:00</a></li>
                        <li><a href="#">0371-63461180</a></li>
                        <li>&nbsp;</li>
                        <li>&nbsp;</li>
                    </ul>
                </div>
                <div class="clear"> </div>
            </div>
            <div class="clear"> </div>
            <!---start-copy-right----->
            <div class="copy-tight">
                <p>
                    <a href="#">关于我们</a>&nbsp;|
                    <a href="#">网站导航</a>&nbsp;|
                    <a href="#">常见问题&帮助</a>&nbsp;|
                    <a href="#">免责声明</a>&nbsp;|
                    <a href="#">投诉&建议</a><br />
                    CopyRight 2009-2015 朔日测评 | 豫ICP备10203241号
                </p>
            </div>
            <!---End-copy-right----->
        </div>
    </div>
    <!---End-footer---->
</body>
</html>